// nuxt-dex/components/Tab.vue
<script lang="ts" setup>
import { getColorsByType } from "~/../library/helpers";
import { useSpeciesStore } from "~/stores/useSpeciesStore";

const store = useSpeciesStore();

const colors = computed(() =>
  Object.values(
    getColorsByType(store.currentVariant.pokemon.types[0].name ?? "")
  ).join(" ")
);

defineProps<{
  active?: boolean;
}>();
</script>

<template>
  <button class="tabs__tab" :class="{ [`!bg-opacity-10 ${colors}`]: active }">
    <slot />
  </button>
</template>

// next-dex/src/components/Tab.tsx
"use client";

import { getColorsByType } from "@/services/helpers";
import clsx from "clsx";
import { useMemo } from "react";
import { useSpeciesContext } from ".";

type Props = React.PropsWithChildren & {
  active?: boolean;
  onClick: () => void;
};

export function Tab({ children, active, onClick }: Props): React.ReactElement {
  const { currentVariant } = useSpeciesContext();

  const colors = useMemo(
    () =>
      Object.values(getColorsByType(currentVariant.types[0].name ?? "")).join(
        " "
      ),
    [currentVariant]
  );

  return (
    <button
      className={clsx("tabs__tab", { [`!bg-opacity-10 ${colors}`]: active })}
      onClick={onClick}
    >
      {children}
    </button>
  );
}
