// nuxt-dex/components/Variants.vue
<script lang="ts" setup>
import { useSpeciesStore } from "~/stores/useSpeciesStore";

const store = useSpeciesStore();

const setCurrentVariant = (variant: object) => {
  store.currentVariant = variant;
};
</script>

<template>
  <Tabs>
    <Tab
      v-for="variant in store.species.varieties"
      :key="variant.pokemon.name"
      @click="setCurrentVariant(variant)"
      :active="store.currentVariant === variant"
    >
      {{ variant.pokemon.name }}
    </Tab>
  </Tabs>
</template>

// next-dex/src/components/Variants.tsx
"use client";

import { Tab, Tabs, useSpeciesContext } from "@/components";
import { formatPokmonName } from "@/services/helpers";

export function Variants(): React.ReactElement {
  const { species, setVariantIndex, variantIndex } = useSpeciesContext();

  return (
    <Tabs>
      {species.varieties.map((variant, index) => (
        <Tab
          key={variant.name}
          onClick={() => setVariantIndex(index)}
          active={index === variantIndex}
        >
          {formatPokmonName(variant.name)}
        </Tab>
      ))}
    </Tabs>
  );
}
